name: Discord Webhook(?)

# 'on' is the trigger, in this case this Action will
# be triggered using cron set at a 10 minutes interval.
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

# 'jobs' are the routines, we only have
# one when the instance is built.
jobs:
  build:
    # Our instance will use the latest available version of Ubuntu.
    runs-on: ubuntu-latest

    # These steps are run in the same order as are defined.
    steps:
      # actions checkout and python are pre-built actions
      # that abstract commonly used tasks.
      - uses: actions/checkout@v2

      # The python action will set us a Python 3.10 (64-bit) instance.
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"

      # Use PIP to install the dependencies and then run the script.
      - name: Running Script
        # But first we read the WEBHOOK secret and create an
        # environment variable with the same name.
        env:
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}
          NOTION_VERSION: ${{ secrets.NOTION_VERSION }}
          DAILY_GOAL: ${{ secrets.DAILY_GOAL }}
          DISCORD_LOGIN_TOKEN: ${{ secrets.DISCORD_LOGIN_TOKEN }}
          KARUNA_ID: ${{ secrets.KARUNA_ID }}
        run: |
          pip install -r requirements.txt
          python index.py
